"""add_embeddings_table

Revision ID: 5c832e56763d
Revises: 83066a162c8c
Create Date: 2026-04-07 14:46:32.712237

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5c832e56763d'
down_revision: str | None = '83066a162c8c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.String(length=255), nullable=False),
    sa.Column('threat_id', sa.String(length=255), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('vector', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('metadata_', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embeddings_chunk_id'), 'embeddings', ['chunk_id'], unique=True)
    op.create_index(op.f('ix_embeddings_id'), 'embeddings', ['id'], unique=False)
    op.create_index(op.f('ix_embeddings_threat_id'), 'embeddings', ['threat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_embeddings_threat_id'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_id'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_chunk_id'), table_name='embeddings')
    op.drop_table('embeddings')
    # ### end Alembic commands ###
