"""initial_schema

Revision ID: 63c50d5f395a
Revises: 
Create Date: 2026-03-27 19:43:12.886906

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '63c50d5f395a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
